# Convert example data files from .csv to .RData
setwd("/Users/mary/Projects/R/packages/DSUR_noof")

data = read.csv("DSUR.noof/inst/extdata/Advert.csv"); save(data, file = "DSUR.noof/data/Advert.RData")
data = read.csv("DSUR.noof/inst/extdata/Album Sales 1.csv"); save(data, file = "DSUR.noof/data/Album Sales 1.RData")
data = read.csv("DSUR.noof/inst/extdata/Album Sales 2.csv"); save(data, file = "DSUR.noof/data/Album Sales 2.RData")
data = read.csv("DSUR.noof/inst/extdata/Attitude.csv"); save(data, file = "DSUR.noof/data/Attitude.RData")
data = read.csv("DSUR.noof/inst/extdata/Beckham(1929).csv"); save(data, file = "DSUR.noof/data/Beckham(1929).RData")
data = read.csv("DSUR.noof/inst/extdata/BeerGogglesLighting.csv"); save(data, file = "DSUR.noof/data/BeerGogglesLighting.RData")
data = read.csv("DSUR.noof/inst/extdata/BigBrother.csv"); save(data, file = "DSUR.noof/data/BigBrother.RData")
data = read.csv("DSUR.noof/inst/extdata/Board&Fritzon(2005).csv"); save(data, file = "DSUR.noof/data/Board&Fritzon(2005).RData")
data = read.csv("DSUR.noof/inst/extdata/Burnout.csv"); save(data, file = "DSUR.noof/data/Burnout.RData")
data = read.csv("DSUR.noof/inst/extdata/Bushtucker.csv"); save(data, file = "DSUR.noof/data/Bushtucker.RData")
data = read.csv("DSUR.noof/inst/extdata/CatRegression.csv"); save(data, file = "DSUR.noof/data/CatRegression.RData")
data = read.csv("DSUR.noof/inst/extdata/CatsandDogs.csv"); save(data, file = "DSUR.noof/data/CatsandDogs.RData")
data = read.csv("DSUR.noof/inst/extdata/Cetinkaya & Domjan (2006).csv"); save(data, file = "DSUR.noof/data/Cetinkaya & Domjan (2006).RData")
data = read.csv("DSUR.noof/inst/extdata/Cetinkaya & Domjan.csv"); save(data, file = "DSUR.noof/data/Cetinkaya & Domjan.RData")
data = read.csv("DSUR.noof/inst/extdata/Chamorro-Premuzic.csv"); save(data, file = "DSUR.noof/data/Chamorro-Premuzic.RData")
data = read.csv("DSUR.noof/inst/extdata/Chat-Up Lines.csv"); save(data, file = "DSUR.noof/data/Chat-Up Lines.RData")
data = read.csv("DSUR.noof/inst/extdata/ChickFlick.csv"); save(data, file = "DSUR.noof/data/ChickFlick.RData")
data = read.csv("DSUR.noof/inst/extdata/ChildAggression.csv"); save(data, file = "DSUR.noof/data/ChildAggression.RData")
data = read.csv("DSUR.noof/inst/extdata/CloakofInvisibility.csv"); save(data, file = "DSUR.noof/data/CloakofInvisibility.RData")
data = read.csv("DSUR.noof/inst/extdata/Contrast.csv"); save(data, file = "DSUR.noof/data/Contrast.RData")
data = read.csv("DSUR.noof/inst/extdata/Cosmetic Surgery.csv"); save(data, file = "DSUR.noof/data/Cosmetic Surgery.RData")
data = read.csv("DSUR.noof/inst/extdata/DarkLord.csv"); save(data, file = "DSUR.noof/data/DarkLord.RData")
data = read.csv("DSUR.noof/inst/extdata/Davey2003.csv"); save(data, file = "DSUR.noof/data/Davey2003.RData")
data = read.csv("DSUR.noof/inst/extdata/Depression.csv"); save(data, file = "DSUR.noof/data/Depression.RData")
data = read.csv("DSUR.noof/inst/extdata/Diet.csv"); save(data, file = "DSUR.noof/data/Diet.RData")
data = read.csv("DSUR.noof/inst/extdata/Display.csv"); save(data, file = "DSUR.noof/data/Display.RData")
data = read.csv("DSUR.noof/inst/extdata/DownloadFestival(No Outlier).csv"); save(data, file = "DSUR.noof/data/DownloadFestival(No Outlier).RData")
data = read.csv("DSUR.noof/inst/extdata/DownloadFestival.csv"); save(data, file = "DSUR.noof/data/DownloadFestival.RData")
data = read.csv("DSUR.noof/inst/extdata/Drug.csv"); save(data, file = "DSUR.noof/data/Drug.RData")
data = read.csv("DSUR.noof/inst/extdata/Dummy.csv"); save(data, file = "DSUR.noof/data/Dummy.RData")
data = read.csv("DSUR.noof/inst/extdata/Eastenders.csv"); save(data, file = "DSUR.noof/data/Eastenders.RData")
data = read.csv("DSUR.noof/inst/extdata/Elephant Football.csv"); save(data, file = "DSUR.noof/data/Elephant Football.RData")
data = read.csv("DSUR.noof/inst/extdata/Escape From Inside.csv"); save(data, file = "DSUR.noof/data/Escape From Inside.RData")
data = read.csv("DSUR.noof/inst/extdata/EssayMarks.csv"); save(data, file = "DSUR.noof/data/EssayMarks.RData")
data = read.csv("DSUR.noof/inst/extdata/Exam Anxiety.csv"); save(data, file = "DSUR.noof/data/Exam Anxiety.RData")
data = read.csv("DSUR.noof/inst/extdata/Facebook.csv"); save(data, file = "DSUR.noof/data/Facebook.RData")
data = read.csv("DSUR.noof/inst/extdata/FacebookNarcissism.csv"); save(data, file = "DSUR.noof/data/FacebookNarcissism.RData")
data = read.csv("DSUR.noof/inst/extdata/Field&Hole.csv"); save(data, file = "DSUR.noof/data/Field&Hole.RData")
data = read.csv("DSUR.noof/inst/extdata/Field(2006).csv"); save(data, file = "DSUR.noof/data/Field(2006).RData")
data = read.csv("DSUR.noof/inst/extdata/Gallup et al.csv"); save(data, file = "DSUR.noof/data/Gallup et al.RData")
data = read.csv("DSUR.noof/inst/extdata/GlastonburyFestivalRegression.csv"); save(data, file = "DSUR.noof/data/GlastonburyFestivalRegression.RData")
data = read.csv("DSUR.noof/inst/extdata/GogglesRegression.csv"); save(data, file = "DSUR.noof/data/GogglesRegression.RData")
data = read.csv("DSUR.noof/inst/extdata/Handlebars.csv"); save(data, file = "DSUR.noof/data/Handlebars.RData")
data = read.csv("DSUR.noof/inst/extdata/HangoverCure.csv"); save(data, file = "DSUR.noof/data/HangoverCure.RData")
data = read.csv("DSUR.noof/inst/extdata/Hiccups.csv"); save(data, file = "DSUR.noof/data/Hiccups.RData")
data = read.csv("DSUR.noof/inst/extdata/Hill et al. (2007).csv"); save(data, file = "DSUR.noof/data/Hill et al. (2007).RData")
data = read.csv("DSUR.noof/inst/extdata/Honeymoon Period.csv"); save(data, file = "DSUR.noof/data/Honeymoon Period.RData")
data = read.csv("DSUR.noof/inst/extdata/Horoscope.csv"); save(data, file = "DSUR.noof/data/Horoscope.RData")
data = read.csv("DSUR.noof/inst/extdata/Infidelity Data.csv"); save(data, file = "DSUR.noof/data/Infidelity Data.RData")
data = read.csv("DSUR.noof/inst/extdata/Infidelity.csv"); save(data, file = "DSUR.noof/data/Infidelity.RData")
data = read.csv("DSUR.noof/inst/extdata/Lacourse et al. (2001) Females.csv"); save(data, file = "DSUR.noof/data/Lacourse et al. (2001) Females.RData")
data = read.csv("DSUR.noof/inst/extdata/Lecturer Data.csv"); save(data, file = "DSUR.noof/data/Lecturer Data.RData")
data = read.csv("DSUR.noof/inst/extdata/LooksOrPersonality.csv"); save(data, file = "DSUR.noof/data/LooksOrPersonality.RData")
data = read.csv("DSUR.noof/inst/extdata/Marzillier & Davey (2005).csv"); save(data, file = "DSUR.noof/data/Marzillier & Davey (2005).RData")
data = read.csv("DSUR.noof/inst/extdata/Matthews et al. (2007).csv"); save(data, file = "DSUR.noof/data/Matthews et al. (2007).RData")
data = read.csv("DSUR.noof/inst/extdata/MenLikeDogs.csv"); save(data, file = "DSUR.noof/data/MenLikeDogs.RData")
data = read.csv("DSUR.noof/inst/extdata/Miller et al. (2007).csv"); save(data, file = "DSUR.noof/data/Miller et al. (2007).RData")
data = read.csv("DSUR.noof/inst/extdata/MixedAttitude.csv"); save(data, file = "DSUR.noof/data/MixedAttitude.RData")
data = read.csv("DSUR.noof/inst/extdata/Muris et al. (2008).csv"); save(data, file = "DSUR.noof/data/Muris et al. (2008).RData")
data = read.csv("DSUR.noof/inst/extdata/Nichols & Nicki (2004).csv"); save(data, file = "DSUR.noof/data/Nichols & Nicki (2004).RData")
data = read.csv("DSUR.noof/inst/extdata/OCD.csv"); save(data, file = "DSUR.noof/data/OCD.RData")
data = read.csv("DSUR.noof/inst/extdata/Penis.csv"); save(data, file = "DSUR.noof/data/Penis.RData")
data = read.csv("DSUR.noof/inst/extdata/ProfilePicture.csv"); save(data, file = "DSUR.noof/data/ProfilePictue.RData")
data = read.csv("DSUR.noof/inst/extdata/RAQ.csv"); save(data, file = "DSUR.noof/data/RAQ.RData")
data = read.csv("DSUR.noof/inst/extdata/RExam.csv"); save(data, file = "DSUR.noof/data/RExam.RData")
data = read.csv("DSUR.noof/inst/extdata/RovingEye.csv"); save(data, file = "DSUR.noof/data/RovingEye.RData")
data = read.csv("DSUR.noof/inst/extdata/SageEditorsCan'tPlayFootball.csv"); save(data, file = "DSUR.noof/data/SageEditorsCan'tPlayFootball.RData")
data = read.csv("DSUR.noof/inst/extdata/Schutzwohl(2008).csv"); save(data, file = "DSUR.noof/data/Schutzwohl(2008).RData")
data = read.csv("DSUR.noof/inst/extdata/Soya.csv"); save(data, file = "DSUR.noof/data/Soya.RData")
data = read.csv("DSUR.noof/inst/extdata/SpiderLong.csv"); save(data, file = "DSUR.noof/data/SpiderLong.RData")
data = read.csv("DSUR.noof/inst/extdata/SpiderWide.csv"); save(data, file = "DSUR.noof/data/SpiderWide.RData")
data = read.csv("DSUR.noof/inst/extdata/Stalker.csv"); save(data, file = "DSUR.noof/data/Stalker.RData")
data = read.csv("DSUR.noof/inst/extdata/Superhero.csv"); save(data, file = "DSUR.noof/data/Superhero.RData")
data = read.csv("DSUR.noof/inst/extdata/Supermodel.csv"); save(data, file = "DSUR.noof/data/Supermodel.RData")
data = read.csv("DSUR.noof/inst/extdata/Teach.csv"); save(data, file = "DSUR.noof/data/Teach.RData")
data = read.csv("DSUR.noof/inst/extdata/TextMessages.csv"); save(data, file = "DSUR.noof/data/TextMessages.RData")
data = read.csv("DSUR.noof/inst/extdata/The Biggest Liar.csv"); save(data, file = "DSUR.noof/data/The Biggest Liar.RData")
data = read.csv("DSUR.noof/inst/extdata/Tumour.csv"); save(data, file = "DSUR.noof/data/Tumour.RData")
data = read.csv("DSUR.noof/inst/extdata/TutorMarks.csv"); save(data, file = "DSUR.noof/data/TutorMarks.RData")
data = read.csv("DSUR.noof/inst/extdata/Viagra.csv"); save(data, file = "DSUR.noof/data/Viagra.RData")
data = read.csv("DSUR.noof/inst/extdata/ViagraCovariate.csv"); save(data, file = "DSUR.noof/data/ViagraCovariate.RData")
data = read.csv("DSUR.noof/inst/extdata/ViagraRobust.csv"); save(data, file = "DSUR.noof/data/ViagraRobust.RData")
data = read.csv("DSUR.noof/inst/extdata/Wii.csv"); save(data, file = "DSUR.noof/data/Wii.RData")
data = read.csv("DSUR.noof/inst/extdata/cats.csv"); save(data, file = "DSUR.noof/data/cats.RData")
data = read.csv("DSUR.noof/inst/extdata/chicken.csv"); save(data, file = "DSUR.noof/data/chicken.RData")
data = read.csv("DSUR.noof/inst/extdata/condom.csv"); save(data, file = "DSUR.noof/data/condom.RData")
data = read.csv("DSUR.noof/inst/extdata/coulrophobia.csv"); save(data, file = "DSUR.noof/data/coulrophobia.RData")
data = read.csv("DSUR.noof/inst/extdata/eel.csv"); save(data, file = "DSUR.noof/data/eel.RData")
data = read.csv("DSUR.noof/inst/extdata/fugazi.csv"); save(data, file = "DSUR.noof/data/fugazi.RData")
data = read.csv("DSUR.noof/inst/extdata/goggles.csv"); save(data, file = "DSUR.noof/data/goggles.RData")
data = read.csv("DSUR.noof/inst/extdata/grades.csv"); save(data, file = "DSUR.noof/data/grades.RData")
data = read.csv("DSUR.noof/inst/extdata/lying.csv"); save(data, file = "DSUR.noof/data/lying.RData")
data = read.csv("DSUR.noof/inst/extdata/pbcorr.csv"); save(data, file = "DSUR.noof/data/pbcorr.RData")
data = read.csv("DSUR.noof/inst/extdata/penalty.csv"); save(data, file = "DSUR.noof/data/penalty.RData")
data = read.csv("DSUR.noof/inst/extdata/psychology.csv"); save(data, file = "DSUR.noof/data/psychology.RData")
data = read.csv("DSUR.noof/inst/extdata/pubs.csv"); save(data, file = "DSUR.noof/data/pubs.RData")
data = read.csv("DSUR.noof/inst/extdata/raq.csv"); save(data, file = "DSUR.noof/data/raq.RData")
data = read.csv("DSUR.noof/inst/extdata/tosse.r.csv"); save(data, file = "DSUR.noof/data/tosse.r.RData")
data = read.csv("DSUR.noof/inst/extdata/williams.csv"); save(data, file = "DSUR.noof/data/williams.RData")

